# Generated by Django 5.2 on 2025-04-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_banned_at_user_banned_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="can_add_superusers",
            new_name="can_add_staff",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="granted_superuser_status_at",
            new_name="granted_staff_status_at",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="granted_superuser_status_by",
            new_name="granted_staff_status_by",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="revoked_superuser_status_at",
            new_name="revoked_staff_status_at",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="revoked_superuser_status_by",
            new_name="revoked_staff_status_by",
        ),
        migrations.AddField(
            model_name="user",
            name="can_revoke_staff",
            field=models.BooleanField(default=False),
        ),
    ]
