# Generated by Django 5.2 on 2025-04-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0002_alter_programinvite_removed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitedorganizationprogram",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="programinvite",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="programsubscriber",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
