# Generated by Django 5.2 on 2025-05-01 14:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0003_alter_invitedorganizationprogram_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EventAdmin",
            new_name="ProgramEventAdmin",
        ),
    ]
