# Generated by Django 5.2 on 2025-05-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0004_rename_eventadmin_programeventadmin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programeventadmin",
            name="role",
            field=models.CharField(default="Admin", max_length=100),
        ),
    ]
