# Generated by Django 5.2 on 2025-05-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_alter_event_archived_by_alter_event_concluded_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="display_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
