# Generated by Django 5.2 on 2025-05-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_alter_attendance_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="short_code",
            field=models.CharField(
                default='import random, string; "".join(random.choices(string.ascii_lowercase, k=8))',
                editable=False,
                max_length=8,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
